version: '3.3'
services:
  web-api:
    build: .
    container_name: web-api
    volumes:
      - ./:/web-api
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    container_name: mariadb-database
